services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    logging:
      options:
        max-size: 1g
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "llmragchatbot"
      MONGO_INITDB_ROOT_PASSWORD: "llmragchatbot"
    volumes:
      - mongo_data:/data/db
    networks:
      - local

volumes:
  mongo_data: 
  
networks:
  local:
    driver: bridge
  